# Generated by Django 5.0.2 on 2024-02-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_storemanager_storelocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='genre',
        ),
    ]
